/** A single page in the exploration history */
export interface PageData {
  /** The user's query or the AI-inferred sub-query */
  query: string;
  /** Unsplash image URL */
  imageUrl: string;
  /** Photographer credit info */
  imageCredit: {
    name: string;
    url: string;
  };
  /** Page title generated by the LLM */
  title: string;
  /** 2-3 sentence description */
  description: string;
  /** Hints for what clicking different regions might explore */
  subtopics: string[];
}

/** POST /api/search request */
export interface SearchRequest {
  query: string;
  breadcrumbs: string[];
  depth: number;
}

/** POST /api/search response */
export interface SearchResponse extends PageData {}

/** POST /api/click request */
export interface ClickRequest {
  x: number; // 0-100 percentage
  y: number; // 0-100 percentage
  imageWidth: number;
  imageHeight: number;
  currentTitle: string;
  currentDescription: string;
  breadcrumbs: string[];
  depth: number;
}

/** POST /api/click response */
export interface ClickResponse {
  subQuery: string;
}

/** The full exploration state kept in the frontend */
export interface ExplorationState {
  pages: PageData[];
  currentDepth: number;
  isLoading: boolean;
  error: string | null;
  maxDepth: number;
}
